### ISSUE TITLE
ssh-agent key functionality ignores IdentityFile

### ISSUE THREAD

**Issue by aisamu** [elpy1/ssh-over-ssm#24]
I ran into an unfortunate corner-case that might be worth documenting/addressing.

I'm a https://github.com/maxgoedjen/secretive user.
One of the things it does is populating the `ssh-agent` with the keys it manages.

Since I'm explicitly setting keys for each host/group via ssh-config's `IdentityFile` (with `IdentitiesOnly yes`), I wasn't even aware of that until I attempted to use `ssh-over-ssm`.

The issue is that the tool picks the _first_ key available on the agent, regardless of it being applicable to that host or not.
This means that the tool was copying the first `ssh-agent` key to the EC2 instance then proceeding to attempt to connect using the `IdentityFile`-defined key.

Thanks for writing this - it's remarkably handy!

**Comment by elpy1** [comment]
Hi,

This is an interesting edge case I haven't come across before. However, I don't think there's an easy fix and I'm not sure it makes sense to try.

When you think about it, by using `ssh-over-ssm` you're basically swapping authentication via sshd for authentication via AWS IAM. This means verification of identity shifts from SSH public key to AWS credentials. Also, there's no real benefit to verifying a user's identity via SSH public key, because if you're permitted to use `ssh-over-ssm`, you're permitted to add/remove any existing keys (via AWS SSM send-command) and connect using any public key (identity).

For your case, I think you'll just need to make minor manual changes to the script to hard-code your key, or something like that. Quite busy at the moment but will get around to adding a note in the README at some point.

Thanks for your report.
